"""initial migration

Revision ID: 17057df566ef
Revises: 
Create Date: 2025-09-07 22:25:00.439459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17057df566ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doente',
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_processo', sa.Integer(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexoenum'), nullable=False),
    sa.Column('morada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internamento',
    sa.Column('numero_internamento', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_alta', sa.Date(), nullable=True),
    sa.Column('doente_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doente_id'], ['doente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internamento')
    op.drop_table('doente')
    # ### end Alembic commands ###
