"""add tipoacidente table and foreign key relationship

Revision ID: 2084421f8f6c
Revises: 32186512025c
Create Date: 2025-09-08 21:26:53.934386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2084421f8f6c'
down_revision: Union[str, Sequence[str], None] = '32186512025c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add TipoAcidente table and foreign key relationship."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create TipoAcidente table
    op.create_table('tipoacidente',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('acidente', sa.String(), nullable=False),
        sa.Column('tipo_acidente', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    # For SQLite, we need to recreate the internamento table to add the foreign key constraint
    # since SQLite doesn't support adding foreign keys to existing tables
    
    # Create new internamento table with foreign key
    op.execute("""
        CREATE TABLE internamento_new (
            id INTEGER NOT NULL PRIMARY KEY,
            numero_internamento INTEGER NOT NULL UNIQUE,
            data_entrada DATE,
            data_alta DATE,
            data_queimadura DATE,
            origem_entrada INTEGER,
            destino_alta INTEGER,
            "ASCQ_total" INTEGER,
            lesao_inalatoria VARCHAR,
            mecanismo_queimadura INTEGER,
            agente_queimadura INTEGER,
            tipo_acidente INTEGER,
            incendio_florestal BOOLEAN,
            contexto_violento VARCHAR,
            suicidio_tentativa BOOLEAN,
            fogueira_queda BOOLEAN,
            lareira_queda BOOLEAN,
            escarotomias_entrada BOOLEAN,
            intubacao_OT VARCHAR,
            "VMI_dias" INTEGER,
            "VNI" BOOLEAN,
            doente_id INTEGER,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(doente_id) REFERENCES doente (id),
            FOREIGN KEY(tipo_acidente) REFERENCES tipoacidente (id)
        )
    """)
    
    # Copy existing data
    op.execute("""
        INSERT INTO internamento_new (
            id, numero_internamento, data_entrada, data_alta, data_queimadura,
            origem_entrada, destino_alta, "ASCQ_total", lesao_inalatoria,
            mecanismo_queimadura, agente_queimadura, tipo_acidente,
            incendio_florestal, contexto_violento, suicidio_tentativa,
            fogueira_queda, lareira_queda, escarotomias_entrada,
            intubacao_OT, "VMI_dias", "VNI", doente_id, created_at, last_modified
        )
        SELECT 
            id, numero_internamento, data_entrada, data_alta, data_queimadura,
            origem_entrada, destino_alta, "ASCQ_total", lesao_inalatoria,
            mecanismo_queimadura, agente_queimadura, tipo_acidente,
            incendio_florestal, contexto_violento, suicidio_tentativa,
            fogueira_queda, lareira_queda, escarotomias_entrada,
            intubacao_OT, "VMI_dias", "VNI", doente_id, created_at, last_modified
        FROM internamento
    """)
    
    # Drop old table and rename new one
    op.drop_table('internamento')
    op.execute("ALTER TABLE internamento_new RENAME TO internamento")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove TipoAcidente table and foreign key relationship."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recreate internamento table without foreign key to tipoacidente
    op.execute("""
        CREATE TABLE internamento_old (
            id INTEGER NOT NULL PRIMARY KEY,
            numero_internamento INTEGER NOT NULL UNIQUE,
            data_entrada DATE,
            data_alta DATE,
            data_queimadura DATE,
            origem_entrada INTEGER,
            destino_alta INTEGER,
            "ASCQ_total" INTEGER,
            lesao_inalatoria VARCHAR,
            mecanismo_queimadura INTEGER,
            agente_queimadura INTEGER,
            tipo_acidente INTEGER,
            incendio_florestal BOOLEAN,
            contexto_violento VARCHAR,
            suicidio_tentativa BOOLEAN,
            fogueira_queda BOOLEAN,
            lareira_queda BOOLEAN,
            escarotomias_entrada BOOLEAN,
            intubacao_OT VARCHAR,
            "VMI_dias" INTEGER,
            "VNI" BOOLEAN,
            doente_id INTEGER,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            last_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(doente_id) REFERENCES doente (id)
        )
    """)
    
    # Copy existing data
    op.execute("""
        INSERT INTO internamento_old (
            id, numero_internamento, data_entrada, data_alta, data_queimadura,
            origem_entrada, destino_alta, "ASCQ_total", lesao_inalatoria,
            mecanismo_queimadura, agente_queimadura, tipo_acidente,
            incendio_florestal, contexto_violento, suicidio_tentativa,
            fogueira_queda, lareira_queda, escarotomias_entrada,
            intubacao_OT, "VMI_dias", "VNI", doente_id, created_at, last_modified
        )
        SELECT 
            id, numero_internamento, data_entrada, data_alta, data_queimadura,
            origem_entrada, destino_alta, "ASCQ_total", lesao_inalatoria,
            mecanismo_queimadura, agente_queimadura, tipo_acidente,
            incendio_florestal, contexto_violento, suicidio_tentativa,
            fogueira_queda, lareira_queda, escarotomias_entrada,
            intubacao_OT, "VMI_dias", "VNI", doente_id, created_at, last_modified
        FROM internamento
    """)
    
    # Drop new table and rename old one
    op.drop_table('internamento')
    op.execute("ALTER TABLE internamento_old RENAME TO internamento")
    
    # Drop TipoAcidente table
    op.drop_table('tipoacidente')
    
    # ### end Alembic commands ###
