"""add traumatipo and trauma tables with foreign key relationships - fixed

Revision ID: b8c76b2c5c11
Revises: f20f382d77a5
Create Date: 2025-09-12 07:57:42.852838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8c76b2c5c11'
down_revision: Union[str, Sequence[str], None] = 'f20f382d77a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traumatipo',
    sa.Column('local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trauma',
    sa.Column('internamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_local', sa.Integer(), nullable=True),
    sa.Column('cirurgia_urgente', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internamento_id'], ['internamento.id'], ),
    sa.ForeignKeyConstraint(['tipo_local'], ['traumatipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Skip foreign key alterations for existing internamento table (SQLite limitation)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trauma')
    op.drop_table('traumatipo')
    # Skip foreign key constraint drops for existing internamento table (SQLite limitation)
    # ### end Alembic commands ###
