"""add localanatomico and queimadura tables with proper foreign keys

Revision ID: cf45754f53ea
Revises: 0409d9abe960
Create Date: 2025-09-11 16:08:13.290639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cf45754f53ea'
down_revision: Union[str, Sequence[str], None] = '0409d9abe960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localanatomico',
    sa.Column('local_anatomico', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('regiao_anatomica', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queimadura',
    sa.Column('internamento_id', sa.Integer(), nullable=False),
    sa.Column('local_anatomico', sa.Integer(), nullable=True),
    sa.Column('grau_maximo', sa.Enum('PRIMEIRO', 'SEGUNDO', 'TERCEIRO', 'QUARTO', name='graumaximoenum'), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internamento_id'], ['internamento.id'], ),
    sa.ForeignKeyConstraint(['local_anatomico'], ['localanatomico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queimadura')
    op.drop_table('localanatomico')
    # ### end Alembic commands ###
