"""add antibiotico, indicacaoantibiotico and internamentoantibiotico tables

Revision ID: e49203047170
Revises: 89b0de97ba33
Create Date: 2025-09-12 09:28:50.776899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e49203047170'
down_revision: Union[str, Sequence[str], None] = '89b0de97ba33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'antibiotico',
        sa.Column('nome_antibiotico', sa.String(), nullable=False),
        sa.Column('classe_antibiotico', sa.String(), nullable=True),
        sa.Column('codigo', sa.String(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'indicacaoantibiotico',
        sa.Column('indicacao', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'internamentoantibiotico',
        sa.Column('internamento_id', sa.Integer(), nullable=False),
        sa.Column('antibiotico', sa.Integer(), nullable=True),
        sa.Column('indicacao', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['antibiotico'], ['antibiotico.id'], ),
        sa.ForeignKeyConstraint(['indicacao'], ['indicacaoantibiotico.id'], ),
        sa.ForeignKeyConstraint(['internamento_id'], ['internamento.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internamentoantibiotico')
    op.drop_table('indicacaoantibiotico')
    op.drop_table('antibiotico')
    # ### end Alembic commands ###
